package com.stockholdergame.client.model {

   [Bindable]
   public class CountryResource {

       public function CountryResource() {
       }

       private static var _instance:CountryResource;

       public static function get instance():CountryResource {
           if (_instance == null) {
               _instance = new CountryResource();
           }
           return _instance;
       }

       public var countriesAndCodes:Array = [
           {n : "Afghanistan",          c : "AF", f : CountryFlagResources.AF},
           {n : "Åland Islands",        c : "AX", f : null},
           {n : "Albania",              c : "AL", f : CountryFlagResources.AL},
           {n : "Algeria",              c : "DZ", f : CountryFlagResources.DZ},
           {n : "American Samoa",       c : "AS", f : CountryFlagResources.AS},
           {n : "Andorra",              c : "AD", f : CountryFlagResources.AD},
           {n : "Angola",               c : "AO", f : CountryFlagResources.AO},
           {n : "Anguilla",             c : "AI", f : CountryFlagResources.AI},
           {n : "Antarctica",           c : "AQ", f : CountryFlagResources.AQ},
           {n : "Antigua and Barbuda",  c : "AG", f : CountryFlagResources.AG},
           {n : "Argentina",            c : "AR", f : CountryFlagResources.AR},
           {n : "Armenia",              c : "AM", f : CountryFlagResources.AM},
           {n : "Aruba",                c : "AW", f : CountryFlagResources.AW},
           {n : "Australia",            c : "AU", f : CountryFlagResources.AU},
           {n : "Austria",              c : "AT", f : CountryFlagResources.AT},
           {n : "Azerbaijan",           c : "AZ", f : CountryFlagResources.AZ},
           {n : "Bahamas",              c : "BS", f : CountryFlagResources.BS},
           {n : "Bahrain",              c : "BH", f : CountryFlagResources.BH},
           {n : "Bangladesh",           c : "BD", f : CountryFlagResources.BD},
           {n : "Barbados",             c : "BB", f : CountryFlagResources.BB},
           {n : "Belarus",              c : "BY", f : CountryFlagResources.BY},
           {n : "Belgium",              c : "BE", f : CountryFlagResources.BE},
           {n : "Belize",               c : "BZ", f : CountryFlagResources.BZ},
           {n : "Benin",                c : "BJ", f : CountryFlagResources.BJ},
           {n : "Bermuda",              c : "BM", f : CountryFlagResources.BM},
           {n : "Bhutan",               c : "BT", f : CountryFlagResources.BT},
           {n : "Bolivia, Plurinational State of",  c : "BO", f : CountryFlagResources.BO},
           {n : "Bonaire, Sint Eustatius and Saba", c : "BQ", f : null},
           {n : "Bosnia and Herzegovina",           c : "BA", f : CountryFlagResources.BA},
           {n : "Botswana",                         c : "BW", f : CountryFlagResources.BW},
           {n : "Bouvet Island",                    c : "BV", f : null},
           {n : "Brazil",                           c : "BR", f : CountryFlagResources.BR},
           {n : "British Indian Ocean Territory",   c : "IO", f : null},
           {n : "Brunei Darussalam",                c : "BN", f : CountryFlagResources.BN},
           {n : "Bulgaria",                         c : "BG", f : CountryFlagResources.BG},
           {n : "Burkina Faso",                     c : "BF", f : CountryFlagResources.BF},
           {n : "Burundi",                          c : "BI", f : CountryFlagResources.BI},
           {n : "Cambodia",                         c : "KH", f : CountryFlagResources.KH},
           {n : "Cameroon",                         c : "CM", f : CountryFlagResources.CM},
           {n : "Canada",                           c : "CA", f : CountryFlagResources.CA},
           {n : "Cape Verde",                       c : "CV", f : CountryFlagResources.CV},
           {n : "Cayman Islands",                   c : "KY", f : CountryFlagResources.KY},
           {n : "Central African Republic",         c : "CF", f : CountryFlagResources.CF},
           {n : "Chad",                             c : "TD", f : CountryFlagResources.TD},
           {n : "Chile",                            c : "CL", f : CountryFlagResources.CL},
           {n : "China",                            c : "CN", f : CountryFlagResources.CN},
           {n : "Christmas Island",                 c : "CX", f : null},
           {n : "Cocos (Keeling) Islands",          c : "CC", f : null},
           {n : "Colombia",                         c : "CO", f : CountryFlagResources.CO},
           {n : "Comoros",                          c : "KM", f : CountryFlagResources.KM},
           {n : "Congo",                            c : "CG", f : CountryFlagResources.CG},
           {n : "Congo, the Democratic Republic of the", c : "CD", f : CountryFlagResources.CD},
           {n : "Cook Islands",                     c : "CK", f : CountryFlagResources.CK},
           {n : "Costa Rica",                       c : "CR", f : CountryFlagResources.CR},
           {n : "Côte d'Ivoire",                    c : "CI", f : CountryFlagResources.CI},
           {n : "Croatia",                          c : "HR", f : CountryFlagResources.HR},
           {n : "Cuba",                             c : "CU", f : CountryFlagResources.CU},
           {n : "Curaçao",                          c : "CW", f : null},
           {n : "Cyprus",                           c : "CY", f : CountryFlagResources.CY},
           {n : "Czech Republic",                   c : "CZ", f : CountryFlagResources.CZ},
           {n : "Denmark",                          c : "DK", f : CountryFlagResources.DK},
           {n : "Djibouti",                         c : "DJ", f : CountryFlagResources.DJ},
           {n : "Dominica",                         c : "DM", f : CountryFlagResources.DM},
           {n : "Dominican Republic",               c : "DO", f : CountryFlagResources.DO},
           {n : "Ecuador",                          c : "EC", f : CountryFlagResources.EC},
           {n : "Egypt",                            c : "EG", f : CountryFlagResources.EG},
           {n : "El Salvador",                      c : "SV", f : CountryFlagResources.SV},
           {n : "Equatorial Guinea",                c : "GQ", f : CountryFlagResources.GQ},
           {n : "Eritrea",                          c : "ER", f : CountryFlagResources.ER},
           {n : "Estonia",                          c : "EE", f : CountryFlagResources.EE},
           {n : "Ethiopia",                         c : "ET", f : CountryFlagResources.ET},
           {n : "Falkland Islands (Malvinas)",      c : "FK", f : null},
           {n : "Faroe Islands",                    c : "FO", f : CountryFlagResources.FO},
           {n : "Fiji",                             c : "FJ", f : CountryFlagResources.FJ},
           {n : "Finland",                          c : "FI", f : CountryFlagResources.FI},
           {n : "France",                           c : "FR", f : CountryFlagResources.FR},
           {n : "French Guiana",                    c : "GF", f : null},
           {n : "French Polynesia",                 c : "PF", f : CountryFlagResources.PF},
           {n : "French Southern Territories",      c : "TF", f : null},
           {n : "Gabon",                            c : "GA", f : CountryFlagResources.GA},
           {n : "Gambia",                           c : "GM", f : CountryFlagResources.GM},
           {n : "Georgia",                          c : "GE", f : CountryFlagResources.GE},
           {n : "Germany",                          c : "DE", f : CountryFlagResources.DE},
           {n : "Ghana",                            c : "GH", f : CountryFlagResources.GH},
           {n : "Gibraltar",                        c : "GI", f : CountryFlagResources.GI},
           {n : "Greece",                           c : "GR", f : CountryFlagResources.GR},
           {n : "Greenland",                        c : "GL", f : CountryFlagResources.GL},
           {n : "Grenada",                          c : "GD", f : CountryFlagResources.GD},
           {n : "Guadeloupe",                       c : "GP", f : CountryFlagResources.GP},
           {n : "Guam",                             c : "GU", f : CountryFlagResources.GU},
           {n : "Guatemala",                        c : "GT", f : CountryFlagResources.GT},
           {n : "Guernsey",                         c : "GG", f : CountryFlagResources.GG},
           {n : "Guinea",                           c : "GN", f : CountryFlagResources.GN},
           {n : "Guinea-Bissau",                    c : "GW", f : CountryFlagResources.GW},
           {n : "Guyana",                           c : "GY", f : CountryFlagResources.GY},
           {n : "Haiti",                            c : "HT", f : CountryFlagResources.HT},
           {n : "Heard Island and McDonald Islands",    c : "HM", f : null},
           {n : "Holy See (Vatican City State)",        c : "VA", f : null},
           {n : "Honduras",                         c : "HN", f : CountryFlagResources.HN},
           {n : "Hong Kong",                        c : "HK", f : CountryFlagResources.HK},
           {n : "Hungary",                          c : "HU", f : CountryFlagResources.HU},
           {n : "Iceland",                          c : "IS", f : CountryFlagResources.IS},
           {n : "India",                            c : "IN", f : CountryFlagResources.IN},
           {n : "Indonesia",                        c : "ID", f : CountryFlagResources.ID},
           {n : "Iran, Islamic Republic of",        c : "IR", f : CountryFlagResources.IR},
           {n : "Iraq",                             c : "IQ", f : CountryFlagResources.IQ},
           {n : "Ireland",                          c : "IE", f : CountryFlagResources.IE},
           {n : "Isle of Man",                      c : "IM", f : CountryFlagResources.IM},
           {n : "Israel",                           c : "IL", f : CountryFlagResources.IL},
           {n : "Italy",                            c : "IT", f : CountryFlagResources.IT},
           {n : "Jamaica",                          c : "JM", f : CountryFlagResources.JM},
           {n : "Japan",                            c : "JP", f : CountryFlagResources.JP},
           {n : "Jersey",                           c : "JE", f : CountryFlagResources.JE},
           {n : "Jordan",                           c : "JO", f : CountryFlagResources.JO},
           {n : "Kazakhstan",                       c : "KZ", f : CountryFlagResources.KZ},
           {n : "Kenya",                            c : "KE", f : CountryFlagResources.KE},
           {n : "Kiribati",                         c : "KI", f : CountryFlagResources.KI},
           {n : "Korea, Democratic People's Republic of",   c : "KP", f : CountryFlagResources.KP},
           {n : "Korea, Republic of",                       c : "KR", f : CountryFlagResources.KR},
           {n : "Kuwait",                                   c : "KW", f : CountryFlagResources.KW},
           {n : "Kyrgyzstan",                               c : "KG", f : CountryFlagResources.KG},
           {n : "Lao People's Democratic Republic",         c : "LA", f : CountryFlagResources.LA},
           {n : "Latvia",                           c : "LV", f : CountryFlagResources.LV},
           {n : "Lebanon",                          c : "LB", f : CountryFlagResources.LB},
           {n : "Lesotho",                          c : "LS", f : CountryFlagResources.LS},
           {n : "Liberia",                          c : "LR", f : CountryFlagResources.LR},
           {n : "Libya",                            c : "LY", f : CountryFlagResources.LY},
           {n : "Liechtenstein",                    c : "LI", f : CountryFlagResources.LI},
           {n : "Lithuania",                        c : "LT", f : CountryFlagResources.LT},
           {n : "Luxembourg",                       c : "LU", f : CountryFlagResources.LU},
           {n : "Macao",                            c : "MO", f : CountryFlagResources.MO},
           {n : "Macedonia, the Former Yugoslav Republic of",   c : "MK", f : CountryFlagResources.MK},
           {n : "Madagascar",                       c : "MG", f : CountryFlagResources.MG},
           {n : "Malawi",                           c : "MW", f : CountryFlagResources.MW},
           {n : "Malaysia",                         c : "MY", f : CountryFlagResources.MY},
           {n : "Maldives",                         c : "MV", f : CountryFlagResources.MV},
           {n : "Mali",                             c : "ML", f : CountryFlagResources.ML},
           {n : "Malta",                            c : "MT", f : CountryFlagResources.MT},
           {n : "Marshall Islands",                 c : "MH", f : CountryFlagResources.MH},
           {n : "Martinique",                       c : "MQ", f : CountryFlagResources.MQ},
           {n : "Mauritania",                       c : "MR", f : CountryFlagResources.MR},
           {n : "Mauritius",                        c : "MU", f : CountryFlagResources.MU},
           {n : "Mayotte",                          c : "YT", f : null},
           {n : "Mexico",                           c : "MX", f : CountryFlagResources.MX},
           {n : "Micronesia, Federated States of",  c : "FM", f : CountryFlagResources.FM},
           {n : "Moldova, Republic of",             c : "MD", f : CountryFlagResources.MD},
           {n : "Monaco",                           c : "MC", f : CountryFlagResources.MC},
           {n : "Mongolia",                         c : "MN", f : CountryFlagResources.MN},
           {n : "Montenegro",                       c : "ME", f : CountryFlagResources.ME},
           {n : "Montserrat",                       c : "MS", f : CountryFlagResources.MS},
           {n : "Morocco",                          c : "MA", f : CountryFlagResources.MA},
           {n : "Mozambique",                       c : "MZ", f : CountryFlagResources.MZ},
           {n : "Myanmar",                          c : "MM", f : CountryFlagResources.MM},
           {n : "Namibia",                          c : "NA", f : CountryFlagResources.NA},
           {n : "Nauru",                            c : "NR", f : CountryFlagResources.NR},
           {n : "Nepal",                            c : "NP", f : CountryFlagResources.NP},
           {n : "Netherlands",                      c : "NL", f : CountryFlagResources.NL},
           {n : "New Caledonia",                    c : "NC", f : CountryFlagResources.NC},
           {n : "New Zealand",                      c : "NZ", f : CountryFlagResources.NZ},
           {n : "Nicaragua",                        c : "NI", f : CountryFlagResources.NI},
           {n : "Niger",                            c : "NE", f : CountryFlagResources.NE},
           {n : "Nigeria",                          c : "NG", f : CountryFlagResources.NG},
           {n : "Niue",                             c : "NU", f : null},
           {n : "Norfolk Island",                   c : "NF", f : null},
           {n : "Northern Mariana Islands",         c : "MP", f : null},
           {n : "Norway",                           c : "NO", f : CountryFlagResources.NO},
           {n : "Oman",                             c : "OM", f : CountryFlagResources.OM},
           {n : "Pakistan",                         c : "PK", f : CountryFlagResources.PK},
           {n : "Palau",                            c : "PW", f : CountryFlagResources.PW},
           {n : "Palestine, State of",              c : "PS", f : CountryFlagResources.PS},
           {n : "Panama",                           c : "PA", f : CountryFlagResources.PA},
           {n : "Papua New Guinea",                 c : "PG", f : CountryFlagResources.PG},
           {n : "Paraguay",                         c : "PY", f : CountryFlagResources.PY},
           {n : "Peru",                             c : "PE", f : CountryFlagResources.PE},
           {n : "Philippines",                      c : "PH", f : CountryFlagResources.PH},
           {n : "Pitcairn",                         c : "PN", f : null},
           {n : "Poland",                           c : "PL", f : CountryFlagResources.PL},
           {n : "Portugal",                         c : "PT", f : CountryFlagResources.PT},
           {n : "Puerto Rico",                      c : "PR", f : CountryFlagResources.PR},
           {n : "Qatar",                            c : "QA", f : CountryFlagResources.QA},
           {n : "Réunion",                          c : "RE", f : CountryFlagResources.RE},
           {n : "Romania",                          c : "RO", f : CountryFlagResources.RO},
           {n : "Russia",                           c : "RU", f : CountryFlagResources.RU},
           {n : "Rwanda",                           c : "RW", f : CountryFlagResources.RW},
           {n : "Saint Barthélemy",                 c : "BL", f : null},
           {n : "Saint Helena, Ascension and Tristan da Cunha",     c : "SH", f : null},
           {n : "Saint Kitts and Nevis",            c : "KN", f : CountryFlagResources.KN},
           {n : "Saint Lucia",                      c : "LC", f : CountryFlagResources.LC},
           {n : "Saint Martin (French part)",       c : "MF", f : null},
           {n : "Saint Pierre and Miquelon",        c : "PM", f : null},
           {n : "Saint Vincent and the Grenadines", c : "VC", f : CountryFlagResources.VC},
           {n : "Samoa",                            c : "WS", f : CountryFlagResources.WS},
           {n : "San Marino",                       c : "SM", f : CountryFlagResources.SM},
           {n : "Sao Tome and Principe",            c : "ST", f : CountryFlagResources.ST},
           {n : "Saudi Arabia",                     c : "SA", f : CountryFlagResources.SA},
           {n : "Senegal",                          c : "SN", f : CountryFlagResources.SN},
           {n : "Serbia",                           c : "RS", f : CountryFlagResources.RS},
           {n : "Seychelles",                       c : "SC", f : CountryFlagResources.SC},
           {n : "Sierra Leone",                     c : "SL", f : CountryFlagResources.SL},
           {n : "Singapore",                        c : "SG", f : CountryFlagResources.SG},
           {n : "Sint Maarten (Dutch part)",        c : "SX", f : null},
           {n : "Slovakia",                         c : "SK", f : CountryFlagResources.SK},
           {n : "Slovenia",                         c : "SI", f : CountryFlagResources.SI},
           {n : "Solomon Islands",                  c : "SB", f : CountryFlagResources.SB},
           {n : "Somalia",                          c : "SO", f : null},
           {n : "South Africa",                     c : "ZA", f : CountryFlagResources.ZA},
           {n : "South Georgia and the South Sandwich Islands",     c : "GS", f : null},
           {n : "South Sudan",                      c : "SS", f : null},
           {n : "Spain",                            c : "ES", f : CountryFlagResources.ES},
           {n : "Sri Lanka",                        c : "LK", f : CountryFlagResources.LK},
           {n : "Sudan",                            c : "SD", f : CountryFlagResources.SD},
           {n : "Suriname",                         c : "SR", f : CountryFlagResources.SR},
           {n : "Svalbard and Jan Mayen",           c : "SJ", f : null},
           {n : "Swaziland",                        c : "SZ", f : CountryFlagResources.SZ},
           {n : "Sweden",                           c : "SE", f : CountryFlagResources.SE},
           {n : "Switzerland",                      c : "CH", f : CountryFlagResources.CH},
           {n : "Syrian Arab Republic",             c : "SY", f : CountryFlagResources.SY},
           {n : "Taiwan, Province of China",        c : "TW", f : CountryFlagResources.TW},
           {n : "Tajikistan",                       c : "TJ", f : CountryFlagResources.TJ},
           {n : "Tanzania, United Republic of",     c : "TZ", f : CountryFlagResources.TZ},
           {n : "Thailand",                         c : "TH", f : CountryFlagResources.TH},
           {n : "Timor-Leste",                      c : "TL", f : CountryFlagResources.TL},
           {n : "Togo",                             c : "TG", f : CountryFlagResources.TG},
           {n : "Tokelau",                          c : "TK", f : null},
           {n : "Tonga",                            c : "TO", f : CountryFlagResources.TO},
           {n : "Trinidad and Tobago",              c : "TT", f : CountryFlagResources.TT},
           {n : "Tunisia",                          c : "TN", f : CountryFlagResources.TN},
           {n : "Turkey",                           c : "TR", f : CountryFlagResources.TR},
           {n : "Turkmenistan",                     c : "TM", f : CountryFlagResources.TM},
           {n : "Turks and Caicos Islands",         c : "TC", f : CountryFlagResources.TC},
           {n : "Tuvalu",                           c : "TV", f : CountryFlagResources.TV},
           {n : "Uganda",                           c : "UG", f : CountryFlagResources.UG},
           {n : "Ukraine",                          c : "UA", f : CountryFlagResources.UA},
           {n : "United Arab Emirates",             c : "AE", f : CountryFlagResources.AE},
           {n : "United Kingdom",                   c : "GB", f : CountryFlagResources.GB},
           {n : "United States",                    c : "US", f : CountryFlagResources.US},
           {n : "United States Minor Outlying Islands",     c : "UM", f : null},
           {n : "Uruguay",                          c : "UY", f : CountryFlagResources.UY},
           {n : "Uzbekistan",                       c : "UZ", f : CountryFlagResources.UZ},
           {n : "Vanuatu",                          c : "VU", f : CountryFlagResources.VU},
           {n : "Venezuela, Bolivarian Republic of",        c : "VE", f : CountryFlagResources.VE},
           {n : "Viet Nam",                         c : "VN", f : CountryFlagResources.VN},
           {n : "Virgin Islands, British",          c : "VG", f : CountryFlagResources.VG},
           {n : "Virgin Islands, U.S.",             c : "VI", f : CountryFlagResources.VI},
           {n : "Wallis and Futuna",                c : "WF", f : null},
           {n : "Western Sahara",                   c : "EH", f : CountryFlagResources.EH},
           {n : "Yemen",                            c : "YE", f : CountryFlagResources.YE},
           {n : "Zambia",                           c : "ZM", f : CountryFlagResources.ZM},
           {n : "Zimbabwe",                         c : "ZW", f : CountryFlagResources.ZW}
       ];

       public function getFlag(countryName:String):Class {
           if (countryName == null) {
               return null;
           }
           for each (var object:Object in countriesAndCodes) {
               if (object.n == countryName) {
                   return object.f;
               }
           }
           return null;
       }

       public var countries:Array = [
           "",
           "Afghanistan",
           "Aland",
           "Albania",
           "Algeria",
           "American Samoa",
           "Andorra",
           "Angola",
           "Anguilla",
           "Antigua and Barbuda",
           "Argentina",
           "Armenia",
           "Aruba",
           "Ascension Island",
           "Australia",
           "Austria",
           "Azerbaijan",
           "Bahamas, The",
           "Bahrain",
           "Bangladesh",
           "Barbados",
           "Belarus",
           "Belgium",
           "Belize",
           "Benin",
           "Bermuda",
           "Bhutan",
           "Bolivia",
           "Bosnia and Herzegovina",
           "Botswana",
           "Brazil",
           "Brunei",
           "Bulgaria",
           "Burkina Faso",
           "Burundi",
           "Cambodia",
           "Cameroon",
           "Canada",
           "Cape Verde",
           "Cayman Islands",
           "Central Africa Republic",
           "Chad",
           "Chile",
           "China",
           "Christmas Island",
           "Cocos (Keeling) Islands",
           "Colombia",
           "Comoros",
           "Congo",
           "Cook Islands",
           "Costa Rica",
           "Cote d'lvoire",
           "Croatia",
           "Cuba",
           "Cyprus",
           "Czech Republic",
           "Denmark",
           "Djibouti",
           "Dominica",
           "Dominican Republic",
           "East Timor Ecuador",
           "Egypt",
           "El Salvador",
           "Equatorial Guinea",
           "Eritrea",
           "Estonia",
           "Ethiopia",
           "Falkland Islands",
           "Faroe Islands",
           "Fiji",
           "Finland",
           "France",
           "French Polynesia",
           "Gabon",
           "Cambia, The",
           "Georgia",
           "Germany",
           "Ghana",
           "Gibraltar",
           "Greece",
           "Greenland",
           "Grenada",
           "Guam",
           "Guatemala",
           "Guemsey",
           "Guinea",
           "Guinea-Bissau",
           "Guyana",
           "Haiti",
           "Honduras",
           "Hong Kong",
           "Hungary",
           "Iceland",
           "India",
           "Indonesia",
           "Iran",
           "Iraq",
           "Ireland",
           "Isle of Man",
           "Israel",
           "Italy",
           "Jamaica",
           "Japan",
           "Jersey",
           "Jordan",
           "Kazakhstan",
           "Kenya",
           "Kiribati",
           "Korea, N",
           "Korea, S",
           "Kosovo",
           "Kuwait",
           "Kyrgyzstan",
           "Laos",
           "Latvia",
           "Lebanon",
           "Lesotho",
           "Liberia",
           "Libya",
           "Liechtenstein",
           "Lithuania",
           "Luxembourg",
           "Macao",
           "Macedonia",
           "Madagascar",
           "Malawi",
           "Malaysia",
           "Maldives",
           "Mali",
           "Malta",
           "Marshall Islands",
           "Mauritania",
           "Mauritius",
           "Mayotte",
           "Mexico",
           "Micronesia",
           "Moldova",
           "Monaco",
           "Mongolia",
           "Montenegro",
           "Montserrat",
           "Morocco",
           "Mozambique",
           "Myanmar",
           "Nagorno-Karabakh",
           "Namibia",
           "Nauru",
           "Nepal",
           "Netherlands",
           "Netherlands Antilles",
           "New Caledonia",
           "New Zealand",
           "Nicaragua",
           "Niger",
           "Nigeria",
           "Niue",
           "Norfolk Island ",
           "Northern Cyprus",
           "Northern Mariana Islands",
           "Norway",
           "Oman",
           "Pakistan",
           "Palau",
           "Palestine",
           "Panama",
           "Papua New Guinea",
           "Paraguay",
           "Peru",
           "Philippines",
           "Pitcaim Islands",
           "Poland",
           "Portugal",
           "Puerto Rico",
           "Qatar",
           "Romania",
           "Russia",
           "Rwanda",
           "Sahrawi Arab Democratic Republic",
           "Saint-Barthelemy",
           "Saint Helena",
           "Saint Kitts and Nevis",
           "Saint Lucia",
           "Saint Martin",
           "Saint Pierre and Miquelon",
           "Saint Vincent and Grenadines",
           "Samos",
           "San Marino",
           "Sao Tome and Principe",
           "Saudi Arabia",
           "Senegal",
           "Serbia",
           "Seychelles",
           "Sierra Leone",
           "Singapore",
           "Slovakia",
           "Slovenia",
           "Solomon Islands",
           "Somalia",
           "Somaliland",
           "South Africa",
           "Spain",
           "Sri Lanka",
           "Sudan",
           "Suriname",
           "Svalbard",
           "Swaziland",
           "Sweden",
           "Switzerland",
           "Syria",
           "Tajikistan",
           "Tanzania",
           "Thailand",
           "Togo",
           "Tokelau",
           "Tonga",
           "Trinidad and Tobago",
           "Tristan da Cunha",
           "Tunisia",
           "Turkey",
           "Turkmenistan",
           "Turks and Caicos Islands",
           "Tuvalu",
           "Uganda",
           "Ukraine",
           "United Arab Emirates",
           "United Kingdom",
           "United States",
           "Uruguay",
           "Uzbekistan",
           "Vanuatu",
           "Vatican City",
           "Venezuela",
           "Vietnam",
           "Virgin Islands, British",
           "Virgin Islands, U.S.",
           "Wallis and Futuna",
           "Yemen",
           "Zambia",
           "Zimbabwe"
       ];
   }
}
